Task 7: repo implementation
ozonva/ova-purchase-api pull request #7
Opened 2021-09-02 09:31 UTC by pelenthium

- [ ] Реализовать методы для интерфейса Repo

- [ ] Заменить в ручках код логирования на работу с repo (+логгирование)

- [ ] Пробросить в конструирование api параметр repo Repo

2021-09-02 15:04 UTC, Miksail requested changes

2021-09-02 15:04 UTC, Miksail commented on cmd/ova-purchase-api/main.go
> +	}
мы запускаем goose отдельной командой через консоль, а не в коде, так как у нас разворачивается сразу 3 инстанса сервиса, одна из goose миграций может упасть, так как например табличка, которую ты создаешь уже создала другая миграция. Убери и для удобства можешь воспользоваться добавить bash скрипт:
export MIGRATION_DIR=./migrations
export DB_PORT="5432"

export DB_NAME="postgres"
export DB_USER="postgres"
export DB_PASSWORD="qwerty"
export DB_HOST="localhost"


export DB_SSL=disable
export PG_DSN="host=${DB_HOST} port=${DB_PORT} dbname=${DB_NAME} user=${DB_USER} sslmode=${DB_SSL} password=${DB_PASSWORD}"


if [ "$1" = "--dryrun" ]; then
    goose -dir ${MIGRATION_DIR} postgres "${PG_DSN}" status -v
else
    goose -dir ${MIGRATION_DIR} postgres "${PG_DSN}" up -v
fi

2021-09-02 15:04 UTC, Miksail commented on db/migration/1_init.sql
> +    status     integer                 not null
сделай статус строковым, вдруг кто то добавит в enum статус между существующими, тогда соответствие int-> status пропадет

2021-09-02 15:04 UTC, Miksail commented on db/migration/1_init.sql
> +-- +goose StatementEnd
добавь -- +goose Down, чтобы миграцию можно было откатить

2021-09-02 15:04 UTC, Miksail commented on db/migration/1_init.sql
> +-- +goose Up
создавай файл миграций при помощи goose create migration_name sql
Он генерирует название файла из текущего времени, таким образом все миграции будут в правильном порядке

2021-09-02 15:04 UTC, Miksail commented on api/ova-purchase-api/ova-purchase-api.proto
> +    string name = 1 [(validate.rules).string.min_len = 1];
добавь ограничение сверху на 255 символов как в БД

2021-09-02 15:04 UTC, Miksail commented on internal/purchase/purchase.go
>  	Id     uint64
указывай аннотации для всех полей

2021-09-02 15:04 UTC, Miksail commented on internal/repo/repo.go
> +
обязательно ставь после начала транзакции defer func() { _ = tx.Rollback()}(), чтобы при выходе с ошибкой она роллбекалась

2021-09-02 15:04 UTC, Miksail commented on internal/repo/repo.go
> +	row := tx.QueryRowContext(ctx, `insert into purchases (user_id, total, updated_at, status) values ($1, $2, $3, $4) RETURNING id`, purchase.UserID, purchase.Total, purchase.UpdatedAt, purchase.Status
не знаю, говорили ли вам что-то про https://github.com/Masterminds/squirrel, но эта штука намного лучше, чем писать чистые sql запросы

2021-09-02 15:04 UTC, Miksail commented on internal/repo/repo.go
> +			select ps.*, i.id as item_id, i.name, i.price, i.quantity from ps left join purchase_items i on i.purchase_id = ps.id
можно разделить на 2 более простых запроса: получить покупки, получить item для покупок. Так и дальнейшая логика будет попроще

2021-09-02 15:04 UTC, Miksail commented on internal/repo/repo.go
> +		log.Error().Msgf("WHAT?")
log.Error().Msgf("can't describe purchase: %v", err)

2021-09-02 15:04 UTC, Miksail commented on internal/repo/repo.go
> +	tx, err := s.db.BeginTxx(ctx, nil)
Rollback

2021-09-02 15:04 UTC, Miksail commented on internal/server/purchase_server.go
> +	}
валидацию можно так-же вынести в отдельный interceptor как и логирование

2021-09-02 15:04 UTC, Miksail commented on internal/server/purchase_server.go
> +	for _, item := range request.Items {
используй геттеры и сеттеры request.GetItems()

2021-09-02 15:04 UTC, Miksail commented on internal/server/purchase_server.go
> +	items := make([]*api.CreatePurchaseResponse_Item, 0)
capacity равный длине created.Items поставь, чтобы память не перевыделялась

2021-09-02 15:04 UTC, Miksail commented on internal/server/purchase_server.go
> +	purchases := make([]*api.Purchase, 0)
укажи capacity

2021-09-02 15:04 UTC, Miksail commented on internal/server/purchase_server.go
> +		return nil, status.Error(codes.NotFound, "Purchase not found")
в go принято писать так, что если у тебя err == nil, то второй параметр никогда не будет nil (и наоборот соотвественно). Т е, эта ошибка должна входить в err

2021-09-02 15:04 UTC, Miksail commented on internal/server/purchase_server.go
> +		return nil, status.Error(codes.NotFound, err.Error())
опять же, вдруг у нас бд шалит, тогда нам нужно отдавать 500. Ошибку формируем в Repo

2021-09-02 15:04 UTC, Miksail commented on internal/server/server.go
> +	api.RegisterPurchaseServiceServer(server, NewPurchaseServer(repo.NewRepo(s.db)))
давай передавать в NewServer сразу PurshaseServer, созданный в main.go

2021-09-02 15:04 UTC, Miksail commented on internal/repo/repo.go
> +type PurchaseRow struct {
структуры описывающие данные хранятся отдельно от Интерфейсов и их имплементаций. Перенеси в repo/datastruct.go

2021-09-03 04:18 UTC, pelenthium commented on cmd/ova-purchase-api/main.go
> +	}
хм, ок, обычно миграции такое умеют,  но гусь не из их числа - https://github.com/pressly/goose/issues/258

2021-09-03 05:16 UTC, pelenthium commented on cmd/ova-purchase-api/main.go
> +	}
да, в java популярный flyway для погреса делает pg_try_advisory_lock с таймаутами и ретраем

2021-09-03 05:17 UTC, pelenthium commented on internal/server/purchase_server.go
> +		return nil, status.Error(codes.NotFound, err.Error())
т/е  репо должно знать какие коды отдавать? кажется что так не должно, вынес эту ошибку в переменную и сравниваю что именно не найдено - тогда код 404 на все другие - 500 будет

2021-09-06 16:01 UTC, Miksail approved these changes

2021-09-07 12:06 UTC, merged