Task 8: MultiCreate operation & kafka & metrics
ozonva/ova-purchase-api pull request #9
Opened 2021-09-07 12:19 UTC by pelenthium

- [ ]  Реализовать MultiCreateEntity ручку для множественного добавления сущностей в базу. Добавление сделать батчами.

 

- [ ] Создавать родительский спан в MultiCreateEntity. На каждый батч нужно создать дочерний спан. В спан добавить размер отправленных данных.

- [ ]  Реализовать UpdateEntity ручку для обновления сущности.

- [ ] Добавить Producer-a для создания CUD событий (Create/Update/Delete) в кафку.
 

- [ ] Добавить метрики на кол-во успешных вызовов для CUD ручек (Create/Update/Delete).

2021-09-07 15:45 UTC, Miksail requested changes

2021-09-07 15:45 UTC, Miksail commented on internal/repo/repo.go
> +	tx, err := s.db.BeginTxx(ctx, nil)
defer rollbackTransaction

2021-09-07 15:45 UTC, Miksail commented on internal/repo/repo.go
> +	tx, err := s.db.BeginTxx(ctx, nil)
defer rollbackTransaction

2021-09-07 15:45 UTC, Miksail commented on internal/repo/repo.go
> +	tx, err := s.db.BeginTxx(ctx, nil)
defer rollbackTransaction

2021-09-07 15:45 UTC, Miksail commented on internal/repo/repo.go
> +	return ids, tx.Commit()
делай tx.Commit() перед return, чтобы Rollback срабатывал

2021-09-08 07:11 UTC, pelenthium commented on internal/repo/repo.go
> +	tx, err := s.db.BeginTxx(ctx, nil)
чуть ниже после проверки err

2021-09-08 07:12 UTC, pelenthium commented on internal/repo/repo.go
> +	tx, err := s.db.BeginTxx(ctx, nil)
https://github.com/ozonva/ova-purchase-api/pull/9/commits/44025a89a31cb24197cf3da0083ba7d42558c11a#diff-d17b58c3ce1bce078384f5ce13114bf74e7536d244b642c238e77853fb83a9ceR213

2021-09-08 08:56 UTC, Miksail approved these changes

2021-09-09 08:34 UTC, merged